name: gsb
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+4
  image_picker_for_web: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/common/assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/src/common/assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: lib/src/common/assets/fonts/Montserrat/Montserrat-Regular.ttf

    - family: JetBrainsMono
      fonts:
        - asset: lib/src/common/assets/fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
        - asset: lib/src/common/assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
