// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqAPl1Gb8mZuNTlWl7s_Lhh6wIrdNt1hw',
    appId: '1:207276688155:web:f40257f352f288764209be',
    messagingSenderId: '207276688155',
    projectId: 'gsbapp-211f3',
    authDomain: 'gsbapp-211f3.firebaseapp.com',
    storageBucket: 'gsbapp-211f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-YgbSwc3lnXjXXCN0exGYhjSyB4ZIxU',
    appId: '1:207276688155:android:235d82dbe9a800744209be',
    messagingSenderId: '207276688155',
    projectId: 'gsbapp-211f3',
    storageBucket: 'gsbapp-211f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZKJk_0bqS8Pn4PtXYVFKHue5J3wcZQA',
    appId: '1:207276688155:ios:e74367dc1e0e35544209be',
    messagingSenderId: '207276688155',
    projectId: 'gsbapp-211f3',
    storageBucket: 'gsbapp-211f3.firebasestorage.app',
    iosBundleId: 'com.example.applicationGsb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZKJk_0bqS8Pn4PtXYVFKHue5J3wcZQA',
    appId: '1:207276688155:ios:e74367dc1e0e35544209be',
    messagingSenderId: '207276688155',
    projectId: 'gsbapp-211f3',
    storageBucket: 'gsbapp-211f3.firebasestorage.app',
    iosBundleId: 'com.example.applicationGsb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqAPl1Gb8mZuNTlWl7s_Lhh6wIrdNt1hw',
    appId: '1:207276688155:web:54eb75002c05dd8a4209be',
    messagingSenderId: '207276688155',
    projectId: 'gsbapp-211f3',
    authDomain: 'gsbapp-211f3.firebaseapp.com',
    storageBucket: 'gsbapp-211f3.firebasestorage.app',
  );
}
